--------------------------------------------------------------------------------
2015-01-12, 10:34:20
--------------------------------------------------------------------------------
<type 'exceptions.ValueError'>: 
array larger than output file, or offset off edge
--------------------------------------------------------------------------------
  File "/Users/dww/Dropbox/svnco/econet/condatis.py", line 836, in exportSourceMap
    self.exportMap(a,"source")
  File "/Users/dww/Dropbox/svnco/econet/condatis.py", line 826, in exportMap
    f=exportgis.createGeoFile(op,driver,a,proj,dtype=dtype)
  File "/Users/dww/Dropbox/svnco/econet/exportgis.py", line 97, in createGeoFile
    DataSet.GetRasterBand(1).WriteArray(np.transpose(a).astype(np.float64))
  File "/Users/dww/anaconda/lib/python2.7/site-packages/osgeo/gdal.py", line 1103, in WriteArray
    return gdalnumeric.BandWriteArray( self, array, xoff, yoff )
  File "/Users/dww/anaconda/lib/python2.7/site-packages/osgeo/gdal_array.py", line 256, in BandWriteArray
    raise ValueError("array larger than output file, or offset off edge")
0.3.85